baseURL = "https://de.shoogle.net/bayern"
languageCode = "de"
title = "Bayern"
theme = "ln-base"

disableKinds = ["RSS", "robotsTXT"]
enableGitInfo = true

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "bayern"

[taxonomies]
  shop = "shops"

